services:
  nginx:
    image: nginx:latest
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HASH}.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.${HASH}.entrypoints=websecure"
      - "traefik.http.routers.${HASH}.tls.certResolver=letsencrypt"
      - "traefik.http.services.${HASH}.loadbalancer.server.port=${API_PORT}"

  whoami:
    image: traefik/whoami
    ports:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
