services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`agility-game.com`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certResolver=letsencrypt"
      - "traefik.http.services.nginx.loadbalancer.server.port=8082"
  whoami:
    image: traefik/whoami
    ports:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
